force_keyboard_focus = true
selection_wrap       = true
theme                = "custom"
additional_theme_location = "~/.local/share/omarchy/default/walker/themes/"
hide_action_hints    = true

[placeholders]
"default" = { input = " Search...", list = "No Results" }

[keybinds]
next             = ["ctrl j"]
previous         = ["ctrl k"]
quick_activate   = []

[columns]
symbols = 1

[providers]
max_results = 256
default = [
  "desktopapplications",
]

[[providers.prefixes]]
prefix = "/"
provider = "providerlist"

[[providers.prefixes]]
prefix = "."
provider = "files"

[[providers.prefixes]]
prefix = ":"
provider = "symbols"

[[providers.prefixes]]
prefix = "="
provider = "calc"

[[providers.prefixes]]
prefix = "@"
provider = "websearch"

[[providers.prefixes]]
prefix = "$"
provider = "clipboard"

[[emergencies]]
text = "Restart Walker"
command = "omarchy-restart-walker"
