stow:
  - zshrc
  - nvim
  - waybar
  - hypr
  - starship
  - ghostty
  - Code
  - branding
  - walker

packages:
  - stow
  - zsh
  - ghostty
  - zen-browser-bin

repos:
  - dest: ~/.local/share/zinit
    url: https://github.com/zdharma-continuum/zinit.git

post:
  - "chsh -s $(command -v zsh) $USER || true"
  - "[ -d ~/.local/share/zinit ] && echo 'zinit installed'"
