stow:
  - zshrc
  - nvim
  - waybar
  - hypr
  - starship
  - ghostty
  - code
  - branding

packages:
  - stow
  - zsh
  - ghostty
  - zen-browser-bin

repos:
  - dest: ~/.local/share/zinit
    url: https://github.com/zdharma-continuum/zinit.git
  - dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    url: https://github.com/zsh-users/zsh-autosuggestions.git
  - dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    url: https://github.com/zsh-users/zsh-syntax-highlighting.git
  - dest: ~/.oh-my-zsh/custom/plugins/zsh-vi-mode
    url: https://github.com/jeffreytse/zsh-vi-mode.git
  - dest: ~/.oh-my-zsh/custom/plugins/zoxide
    url: https://github.com/ajeetdsouza/zoxide.git

post:
  - "chsh -s $(command -v zsh) $USER || true"
  - "[ -d ~/.local/share/zinit ] && echo 'zinit installed'"
